config/routes.rb
 Rails.application.routes.draw do
  get 'publishers/new'

  get 'publishers/create'

  get 'publishers/update'

  get 'publishers/edit'

  get 'publishers/destroy'

  get 'publishers/index'

  get 'publishers/show'

  get 'authors/new'

  get 'authors/create'

  get 'authors/update'

  get 'authors/edit'

  get 'authors/destroy'

  get 'authors/index'

  get 'authors/show'

  get 'categories/new'

  get 'categories/create'

  get 'categories/update'

  get 'categories/edit'

  get 'categories/destroy'

  get 'categories/index'

  get 'categories/show'

  get 'books/new'

  get 'books/create'

  get 'books/update'

  get 'books/edit'

  get 'books/destroy'

  get 'books/index'

  get 'books/show'

  get 'books/new'

  get 'books/create'

  get 'books/update'

  get 'books/edit'

  get 'books/destroy'

  get 'about/index'

  get 'about' => 'about#index'

  root 'books#index'

  resources :books
  resources :authors
  resources :categories
  resources :publishers

end

app/models/author.rb
class Author < ActiveRecord::Base
	has_many :books

	validates :first_name, presence:true
	validates :last_name, presence:true
end

app/models/book.rb
class Book < ActiveRecord::Base
	belongs_to :category
	belongs_to :author
	belongs_to :publisher
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :books


	validates :name, presence: true,
				length: {minimum:3}
end

app/models/publisher.rb
class Publisher < ActiveRecord::Base
	has_many :books

	validates :name, presence:true
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  	@page_title = 'About Us';
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def new
    @page_title = 'Add New Author'
    @author = Author.new
  end

  def create
    @author = Author.new(author_params)
    @author.save

    redirect_to authors_path

  end

  def update
  end

  def edit
  end

  def destroy
  end

  def index
  end

  def show
  end

  private 
    def author_params
      params.require(:author).permit(:first_name, :last_name)
    end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    @page_title = 'Add New Book'
    @book = Book.new
    @category = Category.new
    @author = Author.new
    @publisher = Publisher.new
  end

  def create
    @book = Book.new(book_params)
    @book.save

    redirect_to books_path

  end

  def update
  end

  def edit
  end

  def destroy
  end

  def index
    @book = Book.all
  end

  def show
  end

  private 
    def book_params
    params.require(:book).permit(:title, :category_id, :author_id, :publisher_id, :isbn, :price, :buy, :format, :excerpt, :pages, :year)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def new
    @page_title = 'Add New Category'
    @category= Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = "Category Created"

      redirect_to categories_path
    else 
      render 'new'
    end  
  end

  def update
  end

  def edit
  end

  def destroy
  end

  def index
  end

  def show
  end

  private 
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/publishers_controller.rb
class PublishersController < ApplicationController
  def new
    @page_title = 'Add New Publisher'
    @publisher = Publisher.new
  end

  def create
    @publisher = Publisher.new(publisher_params)
    if @publisher.save
      flash[:notice] = "Publisher Created"
    redirect_to publishers_path
    else
      render 'new'
    end
  end

  def update
  end

  def edit
  end

  def destroy
  end

  def index
  end

  def show
  end

  private 
    def publisher_params
      params.require(:publisher).permit(:name)
    end

end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/publishers_helper.rb
module PublishersHelper
end

app/views/about/index.html.erb
<h1><%= @page_title %></h1>
<p>This is it</p>

app/views/authors/create.html.erb
<h1>Authors#create</h1>
<p>Find me in app/views/authors/create.html.erb</p>

app/views/authors/destroy.html.erb
<h1>Authors#destroy</h1>
<p>Find me in app/views/authors/destroy.html.erb</p>

app/views/authors/edit.html.erb
<h1>Authors#edit</h1>
<p>Find me in app/views/authors/edit.html.erb</p>

app/views/authors/index.html.erb
<h1>Authors#index</h1>
<p>Find me in app/views/authors/index.html.erb</p>

app/views/authors/new.html.erb
<h2> Add New Author</h2>

<%= form_for @author do |f| %>

	<div class="form-group">
		<%= f.label :first_name %><br />
		<%= f.text_field :first_name, class:'form-control' %><br />
	</div>

	<div class="form-group">
		<%= f.label :last_name %><br />
		<%= f.text_field :last_name, class:'form-control' %><br />
	</div>

	<%= f.submit "Submit", class:'btn btn-primary' %>
	<%=link_to "Cancel", authors_path, class:'btn btn-default' %>

<% end %> 

app/views/authors/show.html.erb
<h1>Authors#show</h1>
<p>Find me in app/views/authors/show.html.erb</p>

app/views/authors/update.html.erb
<h1>Authors#update</h1>
<p>Find me in app/views/authors/update.html.erb</p>

app/views/books/create.html.erb
<h1>Books#create</h1>
<p>Find me in app/views/books/create.html.erb</p>

app/views/books/destroy.html.erb
<h1>Books#destroy</h1>
<p>Find me in app/views/books/destroy.html.erb</p>

app/views/books/edit.html.erb
<h1>Books#edit</h1>
<p>Find me in app/views/books/edit.html.erb</p>

app/views/books/index.html.erb
<div id="books-index">
	<div class="row">
		<div class="col-md-3 col-sm-3">
			<h3>HARRY POTTER AND THE SORCERER’S STONE</h3>
			<%= image_tag('hp1.jpg') %>
			<%= link_to 'Read More', book_path(1),  class:'btn btn-primary' %>
		</div>
		<div class="col-md-3 col-sm-3">
			<h3>HARRY POTTER AND THE CHAMBER OF SECRETS</h3>
			<%= image_tag('hp2.jpg') %>
			<%= link_to 'Read More', book_path(1),  class:'btn btn-primary' %>
		</div>
		<div class="col-md-3 col-sm-3">
			<h3>HARRY POTTER AND THE PRISONER OF AZKABAN</h3>
			<%= image_tag('hp3.jpg') %>
			<%= link_to 'Read More', book_path(1),  class:'btn btn-primary' %>
		</div>
		<div class="col-md-3 col-sm-3">
			<h3>HARRY POTTER AND THE <br>GOBLET OF FIRE</h3>
			<%= image_tag('hp4.jpg') %>
			<%= link_to 'Read More', book_path(1),  class:'btn btn-primary' %>
		</div>
	</div>
	<div class="row">
		<div class="col-md-3 col-sm-3"> 
			<h3>HARRY POTTER AND THE ORDER OF THE PHOENIX</h3>
			<%= image_tag('hp5.jpg') %>
			<%= link_to 'Read More', book_path(1),  class:'btn btn-primary' %>
		</div>
		<div class="col-md-3 col-sm-3">
			<h3>HARRY POTTER AND THE HALF-BLOOD PRINCE</h3>
			<%= image_tag('hp6.jpg') %>
			<%= link_to 'Read More', book_path(1),  class:'btn btn-primary' %>
		</div>
		<div class="col-md-3 col-sm-3">
			<h3>HARRY POTTER AND THE <br>DEADLY HALLOWS</h3>
			<%= image_tag('hp7.jpg') %>
			<%= link_to 'Read More', book_path(1),  class:'btn btn-primary' %>
		</div>
		<div class="col-md-3 col-sm-3">
			<h3><br><br>WISHING DAY</h3>
			<%= image_tag('wishingday.jpg') %>
			<%= link_to 'Read More', book_path(1),  class:'btn btn-primary' %>
		</div>
	</div>
</div>

app/views/books/new.html.erb
<h2>Add new book</h2>

<%= form_for @book do |f| %>

	<div class="form-group">
		<%= f.label :title %><br />
		<%= f.text_field :title, class:'form-control' %><br />

	</div>

	<div class="form-group">
		<%= f.label :isbn %><br />
		<%= f.text_field :isbn, class:'form-control' %><br />

	</div>

	<div class="form-group">
		<%= f.label :category %><br />
		<%= f.select :category_id, Category.all.collect {|x| [x.name, x.id]}, {:include_blank => 'Select One'}, class:'form-control' %><br /><br />

	</div>

	<div class="form-group">
		<%= f.label :author %><br />
		<%= f.select :author_id, Author.all.collect {|x| [x.first_name + ' ' + x.last_name, x.id]}, {:include_blank => 'Select One'}, class:'form-control' %><br /><br />

	</div>

	<div class="form-group">
		<%= f.label :publisher %><br />
		<%= f.select :publisher_id, Publisher.all.collect {|x| [x.name, x.id]}, {:include_blank => 'Select One'}, class:'form-control' %><br /><br />

	</div>
	<div class="form-group">
		<%= f.label :format %><br />
		<%= f.text_field :format, class:'form-control' %><br />

	</div>
	<div class="form-group">
		<%= f.label :excerpt %><br />
		<%= f.text_area :excerpt, class:'form-control' %><br />

	</div>
	<div class="form-group">
		<%= f.label :year %><br />
		<%= f.number_field :year, class:'form-control' %><br />

	</div>
	<div class="form-group">
		<%= f.label :coverpath %><br />
		<%= f.number_field :coverpath  , class:'form-control' %><br />

	</div>
	<div class="form-group">
		<%= f.label :pages %><br />
		<%= f.number_field :pages, class:'form-control' %><br />

	</div>
	<div class="form-group">
		<%= f.label :price %><br />
		<%= f.text_field :price, class:'form-control' %><br />

	</div>
	<div class="form-group">
		<%= f.label :buy %><br />
		<%= f.text_field :buy, class:'form-control' %><br />

	</div>

	<%= f.submit "Submit", class:'btn btn-primary' %>
	<%=link_to "Cancel", books_path, class:'btn btn-default' %>

	<% end %>

app/views/books/show.html.erb
<div id="books-show">
	<h2>Harry Potter and the Sorcerer's stone</h2>
	<div class="books-show-left">
		<%= image_tag('hp1.jpg') %>
	</div>
	<div class="books-show-right">
		<h3>Book info:</h3>
		<ul>
			<li><strong>Category: </strong>Harry Potter and the Sorcerer's stone</li>
			<li><strong>Author: </strong>J. K. Rowling</li>
			<li><strong>Publisher: </strong>Bloomsbury (UK) (Canada 2010–present)<br><ol>Arthur A. Levine/Scholastic (US)</ol><ol>Raincoast (Canada 1998–2010)</ol> </li>
			<li><strong>Year: </strong>26 June 1997 (UK)<br><ol>1 September 1998 (US)</ol></li>
			<li><strong>ISBN: </strong>0-7475-3269-9</li>
			<li><strong>Format: </strong>Paperback</li>
			<li><strong>Pages: </strong>249</li>
		</ul>
		<%=link_to "Buy For $5", 'http://www2.sdfi.edu.cn/netclass/jiaoan/englit/download/Harry%20Potter%20and%20the%20Sorcerer\'s%20Stone.pdf', class:'btn btn-success', target:'_blank' %>
	</div>
	<div class="clearfix"></div>
	<h4>Excerpt</h4>
	<p>Mr. and Mrs. Dursley, of number four, Privet Drive, were proud to say
		that they were perfectly normal, thank you very much. They were the last
		people you'd expect to be involved in anything strange or mysterious,
		because they just didn't hold with such nonsense.</p>
	</div>

app/views/books/update.html.erb
<h1>Books#update</h1>
<p>Find me in app/views/books/update.html.erb</p>

app/views/categories/create.html.erb
<h1>Categories#create</h1>
<p>Find me in app/views/categories/create.html.erb</p>

app/views/categories/destroy.html.erb
<h1>Categories#destroy</h1>
<p>Find me in app/views/categories/destroy.html.erb</p>

app/views/categories/edit.html.erb
<h1>Categories#edit</h1>
<p>Find me in app/views/categories/edit.html.erb</p>

app/views/categories/index.html.erb
<h1>Categories#index</h1>
<p>Find me in app/views/categories/index.html.erb</p>

app/views/categories/new.html.erb
<h2> Add New Category</h2>

<%= form_for @category do |f| %>
	<!--Check for errors-->
	<% if @category.errors.any? %>
		<% @category.errors.full_messages.each do |msg| %>
			<!--Show errors -->
			<div class="alert alert-danger"><%= msg %></div>
		<% end %>
	<% end %>		

	<div class="form-group">
		<%= f.label :name %><br />
		<%= f.text_field :name, class:'form-control' %><br />
	</div>

	<%= f.submit "Submit", class:'btn btn-primary' %>
	<%=link_to "Cancel", categories_path, class:'btn btn-default' %>

<% end %> 

app/views/categories/show.html.erb
<h1>Categories#show</h1>
<p>Find me in app/views/categories/show.html.erb</p>

app/views/categories/update.html.erb
<h1>Categories#update</h1>
<p>Find me in app/views/categories/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @page_title ? @page_title : 'Welcome'%> | The BookStore</title>
  <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<nav class="navbar navbar-inverse navbar-fixed-top">
	<div class="container">
	    <div class="navbar-header">
	      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
	        <span class="sr-only">Toggle navigation</span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </button>
	    </div>
	    <div id="navbar" class="collapse navbar-collapse">
	      <ul class="nav navbar-nav">
	        <li class="<%= params[:controller] == 'books' ? 'active' : '' %>"><%= link_to 'Home', root_path %></li>
	        <li class="<%= params[:controller] == 'about' ? 'active' : '' %>"><%= link_to 'About', about_path %></li>
	    </ul>
	    <ul class="nav navbar-right">
          	<li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Add  New<span class="caret"></span></a>
           <ul class="dropdown-menu navbar-right" role="menu">
            <li><%=link_to "Book", new_book_path%></li>
            <li><%=link_to "Category", new_category_path%></li>
            <li><%=link_to "Author", new_author_path%></li>
            <li><%=link_to "Publisher", new_publisher_path%></li>
           
          </ul>
        </li>
	      </ul>
	    </div><!--/.nav-collapse -->
	  </div>
	  </nav>
	  <header>
	  	<div class="container">
	  		<h1>The BookStore <small><%= @page_title ? @page_title : 'Welcome'%></small></h1>
	  	</div>	
	  </header>

	<section>
		<div class="container">
			<div class="row">
				<div class="col-md-8">
					<!--Alerts & Messages-->
				<% if flash[:notice] %> 
				<div class="alert alert-success"><%= flash[:notice] %></div>
				<% end %>

				<% if flash[:alert] %> 
				<div class="alert alert-success"><%= flash[:alert] %></div>
				<% end %>
			<%= yield %>
				</div>
				<div class="col-md-4">
					<%= render 'partials/sidebar' %>
				</div>
			</div>
		</div>
	</section>

	<footer>
		<div class="container">
			<p>Copyright &copy; <%= Time.now.year %> All Right Reserve</p>
	</footer>

</body>
</html>

app/views/partials/_sidebar.html.erb
<% if params[:controller] == 'about' %>
	<div class="well">
		<h3>Location Info</h3>
		<ul>
			<li>The BookStore</li>
			<li>62 Truong Dinh, Hai Ba Trung, Ha Noi</li>
			<li>Phone: 01668236508</li>
			<li>Email: dinhquyf8@gmail.com</li>
		</ul>
	</div>
<% end %>
<% if params[:controller] == 'books' && params[:action] == 'index' || params[:action] == 'show'%>
<div class="list-group">
  <a href="#" class="list-group-item">Novel</a>
  <a href="#" class="list-group-item">Drama</a>
  
</div>
<% end %>

app/views/publishers/create.html.erb
<h1>Publishers#create</h1>
<p>Find me in app/views/publishers/create.html.erb</p>

app/views/publishers/destroy.html.erb
<h1>Publishers#destroy</h1>
<p>Find me in app/views/publishers/destroy.html.erb</p>

app/views/publishers/edit.html.erb
<h1>Publishers#edit</h1>
<p>Find me in app/views/publishers/edit.html.erb</p>

app/views/publishers/index.html.erb
<h1>Publishers#index</h1>
<p>Find me in app/views/publishers/index.html.erb</p>

app/views/publishers/new.html.erb
<h2> Add New Publisher</h2>

<%= form_for @publisher do |f| %>
	<!-- Check for errors -->
	<% if @publisher.errors.any? %>
		<% @publisher.errors.full_messages.each do |msg| %>
		<!-- Show errors -->
			<div class="alert alert-danger"><%= msg %></div>
		<% end %>
	<% end %>
	
	<div class="form-group">
		<%= f.label :name %><br />
		<%= f.text_field :name, class:'form-control' %><br />
	</div>

	<%= f.submit "Submit", class:'btn btn-primary' %>
	<%=link_to "Cancel", publishers_path, class:'btn btn-default' %>

<% end %> 

app/views/publishers/show.html.erb
<h1>Publishers#show</h1>
<p>Find me in app/views/publishers/show.html.erb</p>

app/views/publishers/update.html.erb
<h1>Publishers#update</h1>
<p>Find me in app/views/publishers/update.html.erb</p>